config/routes.rb
SavarCantt::Application.routes.draw do
  resources :applied_vehicle_details

  resources :application_forms

  resources :form_fields

  resources :forms

  resources :users

  resources :vehicles

  resources :vehicle_types

  root :to => 'users#index'
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  # GET /application_forms
  # GET /application_forms.json
  def index
    @application_forms = ApplicationForm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @application_forms }
    end
  end

  # GET /application_forms/1
  # GET /application_forms/1.json
  def show
    @application_form = ApplicationForm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application_form }
    end
  end

  # GET /application_forms/new
  # GET /application_forms/new.json
  def new
    @application_form = ApplicationForm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application_form }
    end
  end

  # GET /application_forms/1/edit
  def edit
    @application_form = ApplicationForm.find(params[:id])
  end

  # POST /application_forms
  # POST /application_forms.json
  def create
    @application_form = ApplicationForm.new(params[:application_form])

    respond_to do |format|
      if @application_form.save
        format.html { redirect_to @application_form, notice: 'Application form was successfully created.' }
        format.json { render json: @application_form, status: :created, location: @application_form }
      else
        format.html { render action: "new" }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /application_forms/1
  # PUT /application_forms/1.json
  def update
    @application_form = ApplicationForm.find(params[:id])

    respond_to do |format|
      if @application_form.update_attributes(params[:application_form])
        format.html { redirect_to @application_form, notice: 'Application form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_forms/1
  # DELETE /application_forms/1.json
  def destroy
    @application_form = ApplicationForm.find(params[:id])
    @application_form.destroy

    respond_to do |format|
      format.html { redirect_to application_forms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/views/application_forms/_form.html.erb
<%= simple_form_for @application_form, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :user_id %>
  <%= f.input :form_id %>
  <%= f.input :request_date %>
  <%= f.input :type_of_move %>
  <%= f.input :purpose, :input_html => { :size => "60x7"} %>
  <%= f.input :duration, :input_html => { :size => "60x1"} %>
  <%= f.input :tracking_id %>
  <%= f.input :status %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                application_forms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/application_forms/edit.html.erb
<%- model_class = ApplicationForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/application_forms/index.html.erb
<%- model_class = ApplicationForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:form_id) %></th>
      <th><%= model_class.human_attribute_name(:request_date) %></th>
      <th><%= model_class.human_attribute_name(:type_of_move) %></th>
      <th><%= model_class.human_attribute_name(:purpose) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:tracking_id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @application_forms.each do |application_form| %>
      <tr>
        <td><%= link_to application_form.id, application_form_path(application_form) %></td>
        <td><%= application_form.user_id %></td>
        <td><%= application_form.form_id %></td>
        <td><%= application_form.request_date %></td>
        <td><%= application_form.type_of_move %></td>
        <td><%= application_form.purpose %></td>
        <td><%= application_form.duration %></td>
        <td><%= application_form.tracking_id %></td>
        <td><%= application_form.status %></td>
        <td><%=l application_form.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_application_form_path(application_form), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      application_form_path(application_form),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_application_form_path,
            :class => 'btn btn-primary' %>

app/views/application_forms/new.html.erb
<%- model_class = ApplicationForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/application_forms/show.html.erb
<%- model_class = ApplicationForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @application_form.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:form_id) %>:</strong></dt>
  <dd><%= @application_form.form_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:request_date) %>:</strong></dt>
  <dd><%= @application_form.request_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_of_move) %>:</strong></dt>
  <dd><%= @application_form.type_of_move %></dd>
  <dt><strong><%= model_class.human_attribute_name(:purpose) %>:</strong></dt>
  <dd><%= @application_form.purpose %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @application_form.duration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tracking_id) %>:</strong></dt>
  <dd><%= @application_form.tracking_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @application_form.status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              application_forms_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_application_form_path(@application_form), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              application_form_path(@application_form),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>