config/routes.rb
SavarCantt::Application.routes.draw do
  resources :applied_vehicle_details

  resources :application_forms

  resources :form_fields

  resources :forms

  resources :users

  resources :vehicles

  resources :vehicle_types

  root :to => 'users#index'
end

app/models/applied_vehicle_detail.rb
class AppliedVehicleDetail < ActiveRecord::Base
  belongs_to :application_form
  belongs_to :vehicle_type
  belongs_to :user
  attr_accessible :quantity
end

app/controllers/applied_vehicle_details_controller.rb
class AppliedVehicleDetailsController < ApplicationController
  # GET /applied_vehicle_details
  # GET /applied_vehicle_details.json
  def index
    @applied_vehicle_details = AppliedVehicleDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applied_vehicle_details }
    end
  end

  # GET /applied_vehicle_details/1
  # GET /applied_vehicle_details/1.json
  def show
    @applied_vehicle_detail = AppliedVehicleDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @applied_vehicle_detail }
    end
  end

  # GET /applied_vehicle_details/new
  # GET /applied_vehicle_details/new.json
  def new
    @applied_vehicle_detail = AppliedVehicleDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @applied_vehicle_detail }
    end
  end

  # GET /applied_vehicle_details/1/edit
  def edit
    @applied_vehicle_detail = AppliedVehicleDetail.find(params[:id])
  end

  # POST /applied_vehicle_details
  # POST /applied_vehicle_details.json
  def create
    @applied_vehicle_detail = AppliedVehicleDetail.new(params[:applied_vehicle_detail])

    respond_to do |format|
      if @applied_vehicle_detail.save
        format.html { redirect_to @applied_vehicle_detail, notice: 'Applied vehicle detail was successfully created.' }
        format.json { render json: @applied_vehicle_detail, status: :created, location: @applied_vehicle_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @applied_vehicle_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applied_vehicle_details/1
  # PUT /applied_vehicle_details/1.json
  def update
    @applied_vehicle_detail = AppliedVehicleDetail.find(params[:id])

    respond_to do |format|
      if @applied_vehicle_detail.update_attributes(params[:applied_vehicle_detail])
        format.html { redirect_to @applied_vehicle_detail, notice: 'Applied vehicle detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @applied_vehicle_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applied_vehicle_details/1
  # DELETE /applied_vehicle_details/1.json
  def destroy
    @applied_vehicle_detail = AppliedVehicleDetail.find(params[:id])
    @applied_vehicle_detail.destroy

    respond_to do |format|
      format.html { redirect_to applied_vehicle_details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/applied_vehicle_details_helper.rb
module AppliedVehicleDetailsHelper
end

app/views/applied_vehicle_details/_form.html.erb
<%= simple_form_for @applied_vehicle_detail, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :application_form_id %>
  <%= f.input :vehicle_type_id %>
  <%= f.input :quantity %>
  <%= f.input :user_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                applied_vehicle_details_path, :class => 'btn' %>
  </div>
<% end %>

app/views/applied_vehicle_details/edit.html.erb
<%- model_class = AppliedVehicleDetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applied_vehicle_details/index.html.erb
<%- model_class = AppliedVehicleDetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:application_form_id) %></th>
      <th><%= model_class.human_attribute_name(:vehicle_type_id) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @applied_vehicle_details.each do |applied_vehicle_detail| %>
      <tr>
        <td><%= link_to applied_vehicle_detail.id, applied_vehicle_detail_path(applied_vehicle_detail) %></td>
        <td><%= applied_vehicle_detail.application_form_id %></td>
        <td><%= applied_vehicle_detail.vehicle_type_id %></td>
        <td><%= applied_vehicle_detail.quantity %></td>
        <td><%= applied_vehicle_detail.user_id %></td>
        <td><%=l applied_vehicle_detail.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_applied_vehicle_detail_path(applied_vehicle_detail), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      applied_vehicle_detail_path(applied_vehicle_detail),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_applied_vehicle_detail_path,
            :class => 'btn btn-primary' %>

app/views/applied_vehicle_details/new.html.erb
<%- model_class = AppliedVehicleDetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applied_vehicle_details/show.html.erb
<%- model_class = AppliedVehicleDetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:application_form_id) %>:</strong></dt>
  <dd><%= @applied_vehicle_detail.application_form_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vehicle_type_id) %>:</strong></dt>
  <dd><%= @applied_vehicle_detail.vehicle_type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @applied_vehicle_detail.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @applied_vehicle_detail.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              applied_vehicle_details_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_applied_vehicle_detail_path(@applied_vehicle_detail), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              applied_vehicle_detail_path(@applied_vehicle_detail),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>