config/routes.rb
SavarCantt::Application.routes.draw do
  resources :applied_vehicle_details

  resources :application_forms

  resources :form_fields

  resources :forms

  resources :users

  resources :vehicles

  resources :vehicle_types

  root :to => 'users#index'
end

app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  # GET /vehicle_types
  # GET /vehicle_types.json
  def index
    @vehicle_types = VehicleType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicle_types }
    end
  end

  # GET /vehicle_types/1
  # GET /vehicle_types/1.json
  def show
    @vehicle_type = VehicleType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle_type }
    end
  end

  # GET /vehicle_types/new
  # GET /vehicle_types/new.json
  def new
    @vehicle_type = VehicleType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle_type }
    end
  end

  # GET /vehicle_types/1/edit
  def edit
    @vehicle_type = VehicleType.find(params[:id])
  end

  # POST /vehicle_types
  # POST /vehicle_types.json
  def create
    @vehicle_type = VehicleType.new(params[:vehicle_type])

    respond_to do |format|
      if @vehicle_type.save
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully created.' }
        format.json { render json: @vehicle_type, status: :created, location: @vehicle_type }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicle_types/1
  # PUT /vehicle_types/1.json
  def update
    @vehicle_type = VehicleType.find(params[:id])

    respond_to do |format|
      if @vehicle_type.update_attributes(params[:vehicle_type])
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_types/1
  # DELETE /vehicle_types/1.json
  def destroy
    @vehicle_type = VehicleType.find(params[:id])
    @vehicle_type.destroy

    respond_to do |format|
      format.html { redirect_to vehicle_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

app/views/vehicle_types/_form.html.erb
<%= simple_form_for @vehicle_type, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :type_name %>
  <%= f.input :description, :input_html => { :size => "60x7"}  %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vehicle_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/vehicle_types/edit.html.erb
<%- model_class = VehicleType -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicle_types/index.html.erb
<%- model_class = VehicleType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:type_name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vehicle_types.each do |vehicle_type| %>
      <tr>
        <td><%= link_to vehicle_type.id, vehicle_type_path(vehicle_type) %></td>
        <td><%= vehicle_type.type_name %></td>
        <td><%= vehicle_type.description %></td>
        <td><%=l vehicle_type.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vehicle_type_path(vehicle_type), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vehicle_type_path(vehicle_type),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vehicle_type_path,
            :class => 'btn btn-primary' %>

app/views/vehicle_types/new.html.erb
<%- model_class = VehicleType -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicle_types/show.html.erb
<%- model_class = VehicleType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:type_name) %>:</strong></dt>
  <dd><%= @vehicle_type.type_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @vehicle_type.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vehicle_types_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vehicle_type_path(@vehicle_type), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vehicle_type_path(@vehicle_type),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>