config/routes.rb
SavarCantt::Application.routes.draw do
  resources :applied_vehicle_details

  resources :application_forms

  resources :form_fields

  resources :forms

  resources :users

  resources :vehicles

  resources :vehicle_types

  root :to => 'users#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Rails Apps</title>
 <%= stylesheet_link_tag    "application", :media => "all" %>
 <%= javascript_include_tag "application" %>
 <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">SavarCantt</a>
        <div class="nav-collapse">
          <ul class="nav">
			<li><%= link_to "DashBoard", "#" %></li>
			<li><%= link_to "Users", users_path %></li>
			<li><%= link_to "VehicleTypes", vehicle_types_path %></li>
			<li><%= link_to "Vehicle", vehicles_path %></li>
			<li><%= link_to "Applications", application_forms_path %></li>
			<li><%= link_to "Forms", forms_path %></li>
			<li><%= link_to "LogOut", "#" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
	<% flash.each do |name, msg|%>
		<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
			<a class="close" data-dismiss="alert" href="#">×</a>
			<%= msg %>
		</div>
	<% end %>
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2><br />
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>
</body>
</html>